name: CI & Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build Multi-plataforma
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            ext: ""
          - goos: windows
            goarch: amd64
            ext: ".exe"
          - goos: darwin
            goarch: amd64
            ext: ""

    defaults:
      run:
        working-directory: projetos/assinatura

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to view tags using git ls-remote

      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: projetos/assinatura/go.sum

      - name: Download Dependencies
        run: go mod download

      - name: Extract Version
        id: version
        shell: bash
        run: |
          # Extrai a versão a partir do código Go
          RAW_VERSION=$(grep -oP 'var version = "\K[^"]+' cmd/version.go)
          VERSION="v$RAW_VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          # Verifica se a tag já existe no repositório
          if git ls-remote --tags origin | grep -q "refs/tags/$VERSION"; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v -o assinatura-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: assinatura-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: projetos/assinatura/assinatura-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
          retention-days: 7

      - name: Upload to GitHub Release & Auto Tag
        uses: softprops/action-gh-release@v2
        if: env.TAG_EXISTS == 'false'
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
          files: projetos/assinatura/assinatura-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
